### ISSUE TITLE
Unable to upload files to CTFD

### ISSUE THREAD

**Issue by ndbellew** [bman46/CTFd-Helm#1]
After working through this helm chart and getting the site up and running I quickly discovered I was unable to upload any files through the ctfd upload media button. 
![image](https://user-images.githubusercontent.com/22332396/194414068-a28a9b47-2acc-46be-8361-44d8f3085d94.png) 
I went into the logs and found this which basically says that the user ctfd does not have root permissions which is a little strange and highly necessary.

**Comment by bman46** [comment]
I dont think its a root user error. Did you configure the helm chart values to request a PVC for the uploads? See the following in the vaules.yaml file.
```
# For uploads to the CTFd server (images and other content)
# Not for DB
persistence:
  uploads:
    enabled: true
    #ReadWriteMany may be desired here if using a multi node cluster.
    accessMode: ReadWriteOnce 
    size: 10Gi
    labels: {}
    # name: value
    # existingClaim:
    # storageClass: "-"

```
Note that the PVC needs to have the access mode `ReadWriteMany` if you are scaling to multiple pods. Otherwise, it will only be able to be used by one pod.
