### ISSUE TITLE
Need extraVolumes, extraVolumeMounts and serviceAccountName as template values

### ISSUE THREAD

**Issue by thibaultserti** [bman46/CTFd-Helm#36]
Hi, I use Vault by Hashicorp to manage my secrets and the CSI provider to sync them in my cluster.
To use this chart, I need some other values to be templated (serviceAccount, extraVolumes and extraVolumesMounts to be templated). 

I would use them like this:

```yaml
serviceAccountName: ctfd
volumeMounts:
  - mountPath: /mnt/secrets-store
    name: secrets-store-inline
volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: <secret-provider-class-name>
```

Will you accept a PR about this matter?
